version: '3'

services:
  backend:
    build: ./backend
    command: flask run --host 0.0.0.0
    ports:
      - 5000:5000
  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - 5173:5173
